Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -53,16 +53,15 @@ jobs:
         run: |
           mkdir -p ${{ env.buildFolder }}/usr/share/pve-manager/js
           mkdir -p ${{ env.buildFolder }}/usr/share/pve-docs/api-viewer
-          mkdir -p ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd
           mkdir -p ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage
+          mkdir -p ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd
           mkdir -p ${{ env.buildFolder }}/usr/share/perl5/REST
 
-          cp plugin-source/truenas-proxmox/pve-manager/js/pvemanagerlib.js ${{ env.buildFolder }}/usr/share/pve-manager/js/
-          cp plugin-source/truenas-proxmox/pve-docs/api-viewer/apidoc.js ${{ env.buildFolder }}/usr/share/pve-docs/api-viewer/
-          cp plugin-source/truenas-proxmox/perl5/PVE/Storage/ZFSPlugin.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/
-          cp plugin-source/truenas-proxmox/perl5/PVE/Storage/LunCmd/TrueNAS.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd/
-          cp plugin-source/truenas-proxmox/perl5/REST/Client.pm ${{ env.buildFolder }}/usr/share/perl5/REST/
-
+          cp plugin-source/pve-manager/js/pvemanagerlib.js ${{ env.buildFolder }}/usr/share/pve-manager/js/
+          cp plugin-source/pve-docs/api-viewer/apidoc.js ${{ env.buildFolder }}/usr/share/pve-docs/api-viewer/
+          cp plugin-source/perl5/PVE/Storage/ZFSPlugin.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/
+          cp plugin-source/perl5/PVE/Storage/LunCmd/TrueNAS.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd/
+          cp plugin-source/perl5/REST/Client.pm ${{ env.buildFolder }}/usr/share/perl5/REST/
         shell: bash
 
       - name: Fix permissions on Debian control scripts
@@ -76,6 +75,26 @@ jobs:
       - name: Build Debian package
         run: |
           sudo dpkg-deb -Zgzip --build ${{ env.buildFolder }} ${{ env.DEB_PACKAGE_NAME }}_${{ env.DEB_PACKAGE_VERSION }}_all.deb
+        shell: bash
+
+      - name: Verify critical files exist before upload
+        run: |
+          REQUIRED_FILES=(
+            "${{ env.buildFolder }}/usr/share/pve-manager/js/pvemanagerlib.js"
+            "${{ env.buildFolder }}/usr/share/pve-docs/api-viewer/apidoc.js"
+            "${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/ZFSPlugin.pm"
+            "${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd/TrueNAS.pm"
+            "${{ env.buildFolder }}/usr/share/perl5/REST/Client.pm"
+          )
+
+          for file in "${REQUIRED_FILES[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "ERROR: Critical file missing: $file"
+              exit 1
+            fi
+          done
+
+          echo "All required plugin files are present."
         shell: bash
 
       - name: Push Debian package to Cloudsmith
